### ISSUE TITLE
Good practice on a method with class in input

### ISSUE THREAD

**Issue by MackJoly** [Dessia-tech/dessia_common#300]
**Note: for support questions, please use https://nextcloud.dessia.tech/call/hr9z9bif

* **I'm submitting a ...**
  - [ ] bug report
  - [ ] feature request

* **What is the current behavior?**
I have a class that inherits from DessiaObject
This class has a method that take inputs : file_component: BinaryFile, sheet: str, _class: DessiaObject

In local, everything work. When i want to push a Workflow in the plateforme using this method (i filled mandatory value such as _class in workflow.imposed_variable_values, so that the plateform doesn't need to ask me this input)

But i have an error 500 in this case

Indeed, the problem comes from to_dict because I have this message : 

  File "C:\Users\Mack\AppData\Local\Temp/ipykernel_8700/3245544341.py", line 1, in <module>
    workflow_0.to_dict()

  File "c:\users\mack\documents\git\dessia_common\dessia_common\workflow\core.py", line 561, in to_dict
    ser_value, memo = serialize_with_pointers(value, memo=memo,

  File "c:\users\mack\documents\git\dessia_common\dessia_common\utils\serialization.py", line 89, in serialize_with_pointers
    serialized = value.to_dict()

TypeError: to_dict() missing 1 required positional argument: 'self' 

self problem should come from the fact that i give a dessiaObject as an input but not instanciated

* **Please tell us about your environment:**
  
  - branch: 
  - commit:  
  - python version:

**Comment by GhislainJ** [comment]
Yes, you are perfectly right. In your typing your are stating that class is an instance of DessiaObject, which in the serialization, will result in dessia_common trying to deseriliase such an instance. At least, it look like so.

You could set your typing as Type for your class_ input. It might fix your issue. By doing so, your class will compute a jsonschema good enough for the frontend to propose a class input. So you won't have to set your value in imposed_variable_values (which mught be broken at the moment)

Note that Type is highly broad and is a temporary solution. In the future you will be able to use SubclassOf[A] to make your typing stricter.

Another note is that it works locally because doesn't enforce typings. So if your inputs are ok for your code, it works fine. The platform in the other hand needs more strictness in order to work properly.

**Comment by MackJoly** [comment]
Hi Ghislain, thank you for your feedback ! I implemented another solution found on the net -> https://stackoverflow.com/questions/1176136/convert-string-to-python-class-object

In fact, I give a string of the class that I want to put in my method, and then I apply a method that will find what class it is
I don't know if it works well but it seems ! I will try your suggestion to see what is better
