### ISSUE TITLE
Label displays (and exports) with decorators

### ISSUE THREAD

**Issue by masfaraud** [Dessia-tech/dessia_common#408]
**Note: for support questions, please use https://nextcloud.dessia.tech/call/hr9z9bif

* **I'm submitting a ...**
  - [ ] bug report
  - [x] feature request

* **What is the current behavior?**
rather than convention on method names

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** Avoid reference to other packages

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

* **Possible fixes**

* **Please tell us about your environment:**
  
  - branch: 
  - commit:  
  - python version:

**Comment by GhislainJ** [comment]
I had a go at this, and it might not be as handy as we thought. 

Though I still think this is the way to go, decorators are not easily found by inspection, from what I read. So we need a but of code that would parse the lines between to definition (class/functions) in order to check for decorator applying to it.

Feature of low-code ?
