### ISSUE TITLE
FullArc3D save_to_file/load_from_file

### ISSUE THREAD

**Issue by GabrielJMS** [Dessia-tech/dessia_common#439]
**Note: for support questions, please use https://nextcloud.dessia.tech/call/hr9z9bif

* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request

* **What is the current behavior?**
Error while trying to read FullArc3D object from volmdlr.edges in a Contour3D. This error arrived after exporting the Contour3D file and trying to read it back to volmdlr object. TypeError: FullArc3D.__init__() missing 2 required positional arguments: 'center' and 'normal'

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
Contour3D.save_to_file() -> Contour3D.load_from_file()

[contour3d_10.zip](https://github.com/Dessia-tech/dessia_common/files/10121434/contour3d_10.zip)

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

* **Possible fixes**

* **Please tell us about your environment:**
  
  - branch: dev
  - commit:  
  - python version: 3.10

**Comment by GhislainJ** [comment]
Hi @GabrielJMS , I just had a quick look and realised the FullArc3D needs `center` and `normal` in its init, but their name are  mangled when set in self (ie `__center` and `__normal`).

I would bet that this is why the save_to_file/load_from_file default behavior don't work (file knows mangled names, and init needs not mangled names).

Do you know why is that ? Is this some kind of standard or convention that you guys use in volmdlr ? In this case, and is this is generic enough, dessia_common could probably handle these, but otherwise, you'll have to overwite the save_to_file function (at least, and it should be easier), in order to store not mangled name in the result file
