### ISSUE TITLE
copy & deep copy error

### ISSUE THREAD

**Issue by ladnane** [Dessia-tech/dessia_common#490]
**Note: for support questions, please use https://nextcloud.dessia.tech/call/hr9z9bif

* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request

* **What is the current behavior?**

copy  (in core) func error when attribute name is different from argument name: 

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** Avoid reference to other packages

using branch `origin/feat/to_dict_id`  for example :
class def:
![Screenshot from 2023-01-16 12-34-17](https://user-images.githubusercontent.com/87009450/212669122-7039e6a9-3e88-42cc-9952-36cbfcdc4eed.png)

![Screenshot from 2023-01-16 12-23-37](https://user-images.githubusercontent.com/87009450/212668588-a405c5e6-9729-490e-9bbd-28c9fd5cce9d.png)

after replacing `attribute` with `bottom_level` , the error disappear:
![Screenshot from 2023-01-16 12-25-47](https://user-images.githubusercontent.com/87009450/212668780-62e9de99-2e4c-468b-87cb-4464dea90213.png)

* **Please tell us about your environment:**
  
  - branch: `origin/feat/to_dict_id`  (based on master)
  - commit:  8a2be94e184db8934e96b6e5f72085b1e991bb50
  - python version: any (3.10)

**Comment by GhislainJ** [comment]
After getting my head back in it, that is the actual behavior. We need to base our copy on class argspecs because we need the right names in order to instantiate the new object.  As we have no way to know links between arg name and attribute name (which could be a composition of a calculus of several args), user need to have stored the value with the same arg name in self.
